### ISSUE TITLE
Gamma-Reward 的公式不能被正确加载

### ISSUE THREAD

**Issue by RingoTC** [multi-commander/Multi-Commander#2]
[Gamma-Reward Algorithm for Multi-Agent](https://github.com/multi-commander/Multi-Commander/blob/master/Multi_Agent/Gamma_reward/README.md)

**Comment by xiawenwen49** [comment]
最新版还没有上传，谢谢关注～

**Comment by Skylark0924** [comment]
本团队还在北京旅行中，最终代码等我们有空再提交
