### ISSUE TITLE
Traffic light baseline comparison

### ISSUE THREAD

**Issue by ThisIsIsaac** [multi-commander/Multi-Commander#3]
Do you have any rule-based non-RL simultions that you used to gauge the performance of RL agents against?

**Comment by xiawenwen49** [comment]
Yes, we have used presslight & max pressure methods, and actually they perform well. The DQN outperforms other RLs for the single intersection scenario.

**Comment by Skylark0924** [comment]
You can see the code in /SingleAgent/Perfect.
It is actually based on rules.

**Comment by ThisIsIsaac** [comment]
oh, I assume **presslight** is when the person in a crosswalk presses a button, and **max pressure** uses rule-based methods and sees the number of cars on each lane to make judgement.

There isn't a method where they take nothing as input, and only cycles through the phases?

**Comment by Skylark0924** [comment]
I do not understand your question since the count of cars on each phase is already an input of MaxPressure
