### ISSUE TITLE
Applying Rainbow DQN

### ISSUE THREAD

**Issue by ThisIsIsaac** [multi-commander/Multi-Commander#5]
I'm trying to add Rainbow DQN agent. Could you share the basics of your environment and point me to a code that I can take a look at to see how to use the environment?

**Comment by xiawenwen49** [comment]
See Multiagent/QMIX&Rule-based/cityflow_env.py

**Comment by ThisIsIsaac** [comment]
There seems to be multiple `CityFlowEnv` classes defined in:
- `Single_Agent/IMPALA/cityflow_env.py`
- `Perfect/test/cityflow_env.py`
- `Single_Agent/Perfect/cityflow_env.py`
- `demo/Demo2/cityflow_env.py`
- `DQN_DDQN_DuelingDQN/test/cityflow_env.py`
- `Single_Agent/DQN_DDQN_DuelingDQN/cityflow_env.py`

How are these related? And how do I know which one to use?

**Comment by xiawenwen49** [comment]
They are modified by different members of our team. The main differences lie in the definition of get_state and get_reward.

**Comment by ThisIsIsaac** [comment]
oh so state and reward representations are different. Thanks.

**Comment by xiawenwen49** [comment]
No problem, and surely you can compare them to see the differences more clearly.
